Add script to create and fill the track and trace contract with items
Concordium/concordium-dapp-examples pull request #45
Opened 2024-01-28 10:19 UTC by DOBEN

## Purpose

A script to initialize a new track-and-trace contract and fill it with items. The status of the items will be updated by the script from `Produced` - > `InTransit` -> `InStore` -> `Sold`. This script helps to have the required contract with events that can be used to test the indexer (to be developed).

## Changes

Add script to create a track-and-trace contract and fill the contract with data for the indexer.

2024-01-28 21:29 UTC, abizjak requested changes

2024-01-28 21:29 UTC, abizjak commented on trackAndTrace/scripts/Cargo.toml
> +concordium-rust-sdk = { version = "4.0"}
Please use the submodule.

2024-01-28 21:29 UTC, abizjak commented on trackAndTrace/scripts/README.md
> +- `--num-items` optional value to specify the number of items to be created in the track-and-trace smart contract. The default value is 1. The states of these items will be updated from 'Produced' ->
I don't think we should be having defualts for arguments like this. This should always be a choice

2024-01-28 21:29 UTC, abizjak commented on trackAndTrace/scripts/README.md
> +cargo run --release -- --node http://node.testnet.concordium.com:20000 --admin-key-file ./4SizPU2ipqQQza9Xa6fUkQBCDjyd1vTNUNDGbBeiRGpaJQc6qX.export --module ./track_and_trace.wasm.v1 --num-items 2
I can't commend on the pictures, but I am not in favor of duplicating "how to export keys from wallet" here.

Screenshots get obsolete quickly. Please just link to the developer documentation. If that data is not there yet add it there instead.

2024-01-28 21:29 UTC, abizjak commented on trackAndTrace/scripts/src/main.rs
> +        default_value = "http://node.testnet.concordium.com:20000",
Please use `https://grpc.testnet.concordium.com` instead since `node` is intended to be deprecated.

2024-01-28 21:29 UTC, abizjak commented on trackAndTrace/scripts/src/main.rs
> +    let admin_key = Arc::new(keys);
Why `Arc`? Does not seem needed.

2024-01-28 21:29 UTC, abizjak commented on trackAndTrace/scripts/src/types.rs
> +}
Why are these types not defined in the contract instead?

2024-01-28 21:29 UTC, abizjak commented on trackAndTrace/scripts/src/types.rs
> +}
Why is this not imported from concordium-std or from the contract?

2024-01-28 21:29 UTC, abizjak commented on trackAndTrace/scripts/src/types.rs
> +}
Isn't this meant to be defined in the contract? Why is it duplicated here?

2024-01-28 21:29 UTC, abizjak commented on trackAndTrace/scripts/src/types.rs
> +}
This is defined in our libraries already.

2024-01-30 07:15 UTC, abizjak commented on trackAndTrace/scripts/src/main.rs
> +        default_value = "http://node.testnet.concordium.com:20000",
So the `grpc.testnet.concordium.com` and `grpc.mainnet.concordium.software` are the public grpc endpoints of the node. I don't know why the names were decided anymore, but those are the links. Let's not revisit the naming again.

There are technical complications with https on the `node` URL. We are aware of annoyances with deprecating it so we're not just going to shut it off, but it will be removed eventually. So please use the link I suggested.

2024-01-31 10:35 UTC, Bargsteen approved these changes
LGTM

2024-02-01 21:10 UTC, abizjak commented on trackAndTrace/scripts/src/main.rs
> +            additional_data: AdditionalData { bytes: vec![] },
Perhaps it's worth adding a `Default` implementation for AdditoinalData to make this a tiny bit nicer.

2024-02-01 21:10 UTC, abizjak commented on trackAndTrace/scripts/README.md
> +This package contains a test script to facilitate filling the track and trace contract with data for the indexer.
It's a bit confusing to me to have this script.

I would expect a script to create a new instance of track and trace with perhaps some new items.

But doing transitions in the script seems odd to me for this reference project.

If something like this is needed for a test I would recommend putting it as an integration test in the smart contract or in some other folder explicitly marked as a test folder.

And these scripts would be just deployment and management scripts that are a normal part of the reference project.

2024-02-01 21:10 UTC, abizjak commented on trackAndTrace/scripts/src/main.rs
> +    // Update items from `InTransit` to `InStore`
I think the script generally looks good, but I don't agree with its scope, namely having this part with transitions.

I believe that should be a separate test.

2024-02-02 10:25 UTC, DOBEN commented on trackAndTrace/scripts/README.md
> +This package contains a test script to facilitate filling the track and trace contract with data for the indexer.
Moved it into a `test_scripts` folder.

2024-02-02 13:49 UTC, DOBEN commented on trackAndTrace/scripts/src/main.rs
> +    // Update items from `InTransit` to `InStore`
The script facilitates to development (as written in the Read.me) of the indexer and as such it is useful to fill the contract with data. 

If in addition, if we want to have an extra deployment script then I agree we should add that to the `smart-contract` folder (hasn't been written yet).

2024-02-02 14:28 UTC, abizjak commented on trackAndTrace/scripts/src/main.rs
> +    // Update items from `InTransit` to `InStore`
So I don't really think we should have this and a separate deployment script that will do most of the same things.

We'll end up with two scripts to maintain, where 80% of the code is almost literal copy paste between them.

I also don't understand the rationale for design.

Assuming you had the deployment script already, then for testing the indexer I would expect you would want something that makes a few transitions over time. So it'd just look up some items and make those transitions and keep doing them.

That would make more sense to me.

2024-02-13 13:53 UTC, abizjak approved these changes

2024-02-13 13:53 UTC, abizjak commented on trackAndTrace/test-scripts/src/main.rs
> +    num_items:                 usize,
It seems like if you set this to be a u64 instead you can avoid `i as u64` conversions.

2024-02-13 13:53 UTC, abizjak commented on trackAndTrace/test-scripts/src/main.rs
> +        }
You could simplify this with the latest rust SDK by using the ModuleDeployBuilder
```rust
            let module =
                WasmModule::from_file(&module_path).context("Could not read contract module.")?;
            let builder =
                ModuleDeployBuilder::dry_run_module_deploy(client, keys.address, module).await?;
            let handle = builder.send(&keys).await?;
            println!("Module deployment transaction {handle} submitted.");
            let result = handle.wait_for_finalization().await?;
            println!("Module {} deployed.", result.module_reference);
```

2024-02-13 13:53 UTC, abizjak commented on trackAndTrace/test-scripts/src/main.rs
> +        contract_client::ContractClient::<TrackAndTraceContract>::create(
You could simplify this by using the ContractInitBuilder
```rust
            let builder = ContractInitBuilder::<WeatherContractMarker>::dry_run_new_instance(
                client,
                account.address,
                mod_ref,
                "track_and_trace",
                Amount::zero(),
                &params,
            )
            .await?;
            println!(
                "The maximum amount of NRG allowed for the transaction is {}.",
                builder.current_energy()
            );
            let handle = builder.send(&account).await?;
            println!("Transaction {handle} submitted. Waiting for finalization.");
            let (contract_client, events) = handle.wait_for_finalization().await?;
            println!(
                "Initialized a new smart contract instance at address {}.",
                contract_client.address
            );

2024-02-13 16:30 UTC, merged