Indexer
Concordium/concordium-dapp-examples pull request #47
Opened 2024-02-01 19:55 UTC by DOBEN

## Purpose

addresses https://github.com/Concordium/concordium-dapp-examples/issues/50

Next: A follow-up PR should include the http server that provides two entrypoints for the front end to query the database.

## Changes

- Add event indexer for the `track-and-trace` project.

2024-02-09 15:27 UTC, abizjak requested changes

2024-02-09 15:27 UTC, abizjak commented on trackAndTrace/indexer/src/main.rs
> +                                }
I really don't like this duplication very much. It would be better to organize this like it is in the bridge indexer

2024-02-09 15:27 UTC, abizjak commented on trackAndTrace/indexer/src/main.rs
> +/// the database. Returns the duration it took to process the transaction.
The problem is that this is not really true. The easy restoration would be much clearer and easier if we inserted in one DB transaction per block.

2024-02-12 12:41 UTC, soerenbf commented on trackAndTrace/indexer/src/main.rs
> +    let mut contrat_set = BTreeSet::new();
```suggestion
    let mut contract_set = BTreeSet::new();
```

2024-02-12 12:41 UTC, soerenbf commented on trackAndTrace/indexer/src/main.rs
> +    let db_pool = DatabasePool::create(app.db_connection.clone(), 2, true)
Maybe I can provide some clarity as to why `2`. This is what I put for the indexer for the GC election project as well. My train of thought was that when attempting to reconnect to the DB you'd have 2 connections until the first one would be dropped (maybe this assumption is wrong, but I thought it couldn't hurt to allow 2 connections for this purpose).

2024-02-12 12:41 UTC, soerenbf commented on trackAndTrace/indexer/resources/schema.sql
> +  latest_event_index INT8,
This would also be redundant if we commit per block

2024-02-12 12:41 UTC, soerenbf commented on trackAndTrace/indexer/resources/schema.sql
> +  block_height INT8 NOT NULL,
Why is block height interesting? If it is to make it possible to order the data by something from the chain, would it not be better to add the block time instead, as it would probably be more interesting for the consumer of the data?

2024-02-12 12:41 UTC, soerenbf commented on trackAndTrace/indexer/resources/schema.sql
> +  block_height INT8 NOT NULL,
Also here

2024-02-12 13:01 UTC, limemloh commented on trackAndTrace/indexer/resources/schema.sql
> +  id INT8 PRIMARY KEY,
**Suggestion:** It seems that we are incrementing this ID manually in the insert query, consider using [BIGSERIAL](https://www.postgresql.org/docs/current/datatype-numeric.html) instead

2024-02-12 13:44 UTC, limemloh commented on trackAndTrace/indexer/src/main.rs
> +        }
**Suggestion:** Signalling the service to stop, will not actually stop until the indexer receives a new block, which is not the end of the world, but not ideal.

```suggestion
    let shutdown_signal = set_shutdown();
    // The indexer starts processing historical events and then listens for new
    // events that are coming in as the blockchain progresses.
    loop {
        let (block, contract_update_infos) = tokio::select! {
            biased;
            _ = shutdown_signal => { break },
            Some(v) = receiver.recv() => v,
            else => { break }
        };
```
The above is not really tested, but it should remove the need for `stop_flag` as well

2024-02-12 14:12 UTC, abizjak commented on trackAndTrace/indexer/src/main.rs
> +                                    };
It's just that there is no point with having the pool for the indexer. So I don't like having things that don't have a point.

2024-02-12 14:26 UTC, abizjak commented on trackAndTrace/indexer/resources/schema.sql
> +  id INT8 PRIMARY KEY,
It would be better to do it explicitly since it will probably be leaked in queries for pagination, etc.

SERIAL does not guarantee that there are no gaps, and you can see in practice if transactions are rolled back for example that there will be gaps in IDs.

While this does not matter for storage, these IDs will likely be exposed for pagination purposes in queries, so some clients are bound to rely on them. Since it's easy to ensure they consistent and deterministic, we should do so.

2024-02-12 17:02 UTC, DOBEN commented on trackAndTrace/indexer/resources/schema.sql
> +  CONSTRAINT unique_item_status_changed UNIQUE (block_height, transaction_hash, event_index)
It is not unique if we want to refer to a specific event in a general smart contract. Since the indexer should be generic enough to apply to any contract, this is tracked here.

For our specific smart contract example: yes the transaction hash would be enough to uniquely identify an event.

2024-02-12 19:57 UTC, DOBEN commented on trackAndTrace/indexer/src/main.rs
> +        env = "CCD_INDEXER_START"
It is the block height now.

2024-02-13 09:08 UTC, DOBEN commented on trackAndTrace/indexer/resources/schema.sql
> +  block_height INT8 NOT NULL,
I added the `block_time` to the database, which is now returned when querying the rows of the database. In addition, I kept the `block_height` in the database because it will allow to figure out which is the last `block_height` that was processed to be able to re-start the indexer.

The indexer starts by providing it the `block_height` to start from. The `block_time` is hard to copy-paste from CCDScan in the way it is presented at the moment.

2024-02-13 10:28 UTC, DOBEN commented on trackAndTrace/indexer/src/main.rs
> +    let db_pool = DatabasePool::create(app.db_connection.clone(), 2, true)
I got inspiration from @soerenbf's great work on the GC election project :). 

Nonetheless, I changed the value to 1 now since we commit one DB transaction per block now without any re-try logic.

2024-02-13 10:55 UTC, DOBEN commented on trackAndTrace/indexer/src/main.rs
> +                                    };
As Soeren already mentioned, the `http` server should access the DB as well through the pool. Next time, it should be added in the next PR, agree. For now, I kept the DB pool in this PR so.

2024-02-14 10:21 UTC, DOBEN commented on trackAndTrace/smart-contract/Cargo.toml
> +concordium-contracts-common = "9.0.0"
It is needed because the feature `derive-serde` includes `concordium-contracts-common/derive-serde`. `Concordium-contracts-common` needs to be a dependency otherwise we cannot expose the `derive-serde` feature.

Applied your suggestion of using the wildcard character.

2024-02-14 10:29 UTC, DOBEN commented on trackAndTrace/smart-contract/Cargo.toml
> +derive-serde = ["concordium-contracts-common/derive-serde", "serde"]
We also have a dependency called `serde` and this causes an error:
```
    Caused by:
         optional dependency `serde` is not included in any feature
         Make sure that `dep:serde` is included in one of features in the [features] table.

```

2024-02-14 11:53 UTC, DOBEN commented on trackAndTrace/indexer/README.md
> +cargo run -- --node https://grpc.testnet.concordium.com:20000 --start 2024-01-28T10:12:30Z --contract "<7835,0>"
I use the block_height now. Since that value is easily obtained from `CCDScan` by copy-paste.

2024-02-14 12:01 UTC, DOBEN commented on trackAndTrace/indexer/src/main.rs
> +
The above check in the code, just ensured that we have correctly written the contract_address to the database.

2024-02-14 13:01 UTC, Bargsteen approved these changes
Nice work 👍

2024-02-15 10:18 UTC, abizjak reviewed
Looks pretty good.

But I feel very strongly that the indexer should be able to restart without user intervention. This allows for maintenance for example.

2024-02-15 10:18 UTC, abizjak commented on trackAndTrace/indexer/Cargo.toml
> +tracing-subscriber = "0.3.18"
```suggestion
tracing-subscriber = "0.3"
```

2024-02-15 10:18 UTC, abizjak commented on trackAndTrace/indexer/Cargo.toml
> +tracing = "0.1.40"
```suggestion
tracing = "0.1"
```

2024-02-15 10:18 UTC, abizjak commented on trackAndTrace/indexer/Cargo.toml
> +futures = "0.3.30"
```suggestion
futures = "0.3"
```

2024-02-15 10:18 UTC, abizjak commented on trackAndTrace/indexer/README.md
> +In case the indexer stops, after fixing the cause of the failure the indexer can be re-started by providing as `--start` option the `latest_processed_block_height + 1`. You can figure out the latest
I don't think we should be having this --start option. THis should be automatically discovered like it is for the transaction logger, and other indexers we have.

2024-02-15 10:18 UTC, abizjak commented on trackAndTrace/indexer/resources/schema.sql
> +);
The indexer should store the last processed heigh or block, whatever is easiest.

So that restarting it requires no manual user intervention. This is what we want from all indexers. It is less error prone.

2024-02-15 10:18 UTC, abizjak commented on trackAndTrace/indexer/resources/schema.sql
> +  block_height INT8 NOT NULL,
As I wrote in the comment above, the "settings" or another table if you want should store the "last processed block". So that restarting requires no user intervention.

If we ask the user to do it they will do it wrong, and we might skip events, or risk duplicates (unless we have enough database rules).

2024-02-15 10:18 UTC, abizjak commented on trackAndTrace/indexer/src/main.rs
> +            for tx in contract_update_infos {
The Rust SDK 4.2.0 is published now, so you might want to use that  to simplify this loop.

2024-02-15 10:19 UTC, abizjak commented on trackAndTrace/indexer/resources/schema.sql
> +);
Since you are processing blocks atomically you can, in the same DB transaction, also update this height. That will ensure consistency.

2024-02-21 07:47 UTC, abizjak approved these changes

2024-02-21 07:47 UTC, abizjak commented on trackAndTrace/indexer/src/main.rs
> +            Ok(_) => Ok(true),
I don't think this will work. You want to set the active connection to this one, so
```
Ok(conn) => {
    self.db = conn;
}
```

2024-02-21 07:47 UTC, abizjak commented on trackAndTrace/indexer/src/main.rs
> +                            target:"ccd_event_processor",
I'd recommend not setting an explicit target here so that it's clear that logs are comming from this module instead.

2024-02-21 07:47 UTC, abizjak commented on trackAndTrace/indexer/src/main.rs
> +    db_pool: DatabasePool,
I think if you want to use a DatabasePool you should not keep a connection here as well, even though it is not wrong to do so.

I'd recommend just doing

```
let conn = db_pool.get().await?;
let db_transaction = conn.client.transaction().await...
```
inside the "process" method.

2024-02-21 07:47 UTC, abizjak commented on trackAndTrace/indexer/src/main.rs
> +        {
If you follow my suggestion above then the "on_failure" does not really have to do anything other than log.

2024-02-21 09:21 UTC, limemloh approved these changes

2024-02-21 12:22 UTC, merged