Server track and trace
Concordium/concordium-dapp-examples pull request #57
Opened 2024-02-26 14:20 UTC by DOBEN

## Purpose

_Describe the purpose of the pull request, link to issue describing the problem, etc.

## Changes

_Describe the changes that were needed.

## Checklist

- [ ] My code follows the style of this project.
- [ ] The code compiles without warnings.
- [ ] I have performed a self-review of the changes.
- [ ] I have documented my code, in particular the intent of the
      hard-to-understand areas.
- [ ] (If necessary) I have updated the CHANGELOG.

## CLA acceptance

_Remove if not applicable.

By submitting the contribution I accept the terms and conditions of the
Contributor License Agreement v1.0
- link: https://developers.concordium.com/CLAs/Contributor-License-Agreement-v1.0.pdf

- [ ] I accept the above linked CLA.

2024-02-28 20:55 UTC, abizjak requested changes

2024-02-28 20:55 UTC, abizjak commented on sponsoredTransactionsAuction/backend/src/main.rs
> +          println!("Server has shut down gracefully");
You should not `print`, you should use `tracing::info`.

2024-02-28 20:55 UTC, abizjak commented on sponsoredTransactionsAuction/backend/src/main.rs
> +      }
I don't understand why you removed the `with_graceful_shutdown`. That is supposed to ensure that existing clients are served before the server shuts down.

The way you have it now means the server is just killed very ungracefully.

2024-02-28 20:55 UTC, abizjak commented on trackAndTrace/indexer/src/bin/server.rs
> +                    Json(format!("{}", error)),
We don't want to be returning internal errors to clients. It might accidentally leak sensitive information.

2024-02-28 20:55 UTC, abizjak commented on trackAndTrace/indexer/src/bin/server.rs
> +                (StatusCode::INTERNAL_SERVER_ERROR, Json(error.to_string()))
We don't want to be returning internal errors to clients. It might accidentally leak sensitive information.

2024-02-28 20:55 UTC, abizjak commented on trackAndTrace/indexer/src/bin/server.rs
> +                    Json(format!("{}", error)),
We don't want to be returning internal errors to clients. It might accidentally leak sensitive information.

2024-02-28 20:55 UTC, abizjak commented on trackAndTrace/indexer/src/bin/server.rs
> +            error => {
Please make all the cases explicit for better maintainability.

2024-02-28 20:55 UTC, abizjak commented on trackAndTrace/indexer/src/bin/server.rs
> +        long = "port",
This should not be called port, it is the entire listen-address.

2024-02-28 20:55 UTC, abizjak commented on trackAndTrace/indexer/src/bin/server.rs
> +    let index_template = fs::read_to_string(app.frontend_assets.join("index.html"))
Why is this called a "template" when it's just a file?

2024-02-28 20:55 UTC, abizjak commented on trackAndTrace/indexer/src/bin/server.rs
> +    }
Please use with_graceful_shutdown for the server, not this.

2024-02-28 20:55 UTC, abizjak commented on trackAndTrace/indexer/src/bin/server.rs
> +#[tracing::instrument(level = "info")]
This will print the entire state in the log. We don't need that.

2024-02-28 20:55 UTC, abizjak commented on trackAndTrace/indexer/src/bin/server.rs
> +async fn get_item_created_event(
Same as above, we don't want to print all the parameters.

2024-02-28 20:55 UTC, abizjak commented on trackAndTrace/indexer/src/bin/server.rs
> +        .await?;
This is not really acceptable. It is just incorrect to always go from 0. So we have to add additional (optional) parameters to the request, limit and offset.

And guard that the limit is not too large.

2024-03-01 13:57 UTC, abizjak approved these changes

2024-03-01 13:57 UTC, abizjak commented on trackAndTrace/indexer/src/bin/server.rs
> +    }
In the wallet-proxy we just take the `min(MAX_REQUEST_LIMIT, param.limit)`. 

Both options are fine with me, I'm just wondering why you chose to reject the request.

2024-03-01 13:57 UTC, abizjak commented on trackAndTrace/indexer/src/bin/server.rs
> +    #[error("The requested events to the database where above the limit {0}")]
```suggestion
    #[error("The requested events to the database were above the limit {0}")]
```

2024-03-01 16:32 UTC, DOBEN commented on trackAndTrace/indexer/src/bin/server.rs
> +    }
My thinking was along the way, that it is easier to catch from the front end that pagination needs to be implemented if the request reverts rather than returning silently fewer items than requested.

2024-03-01 16:38 UTC, merged