initial commit of the low-code nft marketplace
Concordium/concordium-dapp-examples pull request #8
Opened 2023-03-23 11:41 UTC by bogacyigitbasi

## Purpose

_Describe the purpose of the pull request, link to issue describing the problem, etc.

## Changes

_Describe the changes that were needed.

## Checklist

- [x] My code follows the style of this project.
- [x] The code compiles without warnings.
- [x] I have performed a self-review of the changes.
- [x] I have documented my code, in particular the intent of the
      hard-to-understand areas.
- [ ] (If necessary) I have updated the CHANGELOG.

## CLA acceptance

_Remove if not applicable.

By submitting the contribution I accept the terms and conditions of the
Contributor License Agreement v1.0
- link: https://developers.concordium.com/CLAs/Contributor-License-Agreement-v1.0.pdf

- [x] I accept the above linked CLA.

2023-04-12 18:53 UTC, abizjak requested changes
Most of it looks pretty good, but there are a few things that need to be changed

- I don't think we should have a duplicate copy of the CIS2-multi contract. We  should work to get the one in rust-smart-contracts modified if practical.
- There is a bunch of duplication for generic stuff for interacting with CIS2 contracts. That should be moved to the node SDK and the duplication should be removed.
- The typescript projects should have linting as well.
- Cargo.lock files should be committed for contracts.

2023-04-12 18:53 UTC, abizjak commented on low-code-nft-marketplace/README.md
> +This repository provides sample implementations of following ways in which a developer can interact with an on chain contract on Concordium.This repo includes both minting tool and the NFT Marketplac
"This repository provides sample implementations of following ways " does not read very well.

2023-04-12 18:53 UTC, abizjak commented on low-code-nft-marketplace/cis2-market/.gitignore
> +Cargo.lock
Cargo.lock should be committed for binaries.

2023-04-12 18:53 UTC, abizjak commented on low-code-nft-marketplace/cis2-market/src/cis2_client.rs
> +                SupportResult::SupportBy(_) => false,
What is the reasoning for this choice?

2023-04-12 18:53 UTC, abizjak commented on low-code-nft-marketplace/cis2-market/src/cis2_client.rs
> +    pub(crate) fn supports_cis2<S: HasStateApi, T: IsTokenId, A: IsTokenAmount + Copy>(
Why are all of these just pub(crate)?

2023-04-12 18:53 UTC, abizjak commented on low-code-nft-marketplace/cis2-market/src/cis2_client.rs
> +        entrypoint_name: &str,
We have EntrypointName type. I think it would be better to use it than str.

2023-04-12 18:53 UTC, abizjak commented on low-code-nft-marketplace/cis2-market/src/cis2_client.rs
> +    fn invoke_contract_read_only<
I am not sure why this function exists. Can you document.

In general all of the above functions should be documented.

2023-04-12 18:53 UTC, abizjak commented on low-code-nft-marketplace/cis2-market/src/params.rs
> +    pub commission: u16,
Please document the meaning here. It is unclear how u16 converts to a commission percentage.

2023-04-12 18:53 UTC, abizjak commented on low-code-nft-marketplace/cis2-market/src/params.rs
> +    pub cis_contract_address: ContractAddress,
Please explain what the meaning of this field is.

2023-04-12 18:53 UTC, abizjak commented on low-code-nft-marketplace/cis2-market/src/state.rs
> +    pub(crate) fn get_listed(
Documentation missing.

2023-04-12 18:53 UTC, abizjak commented on low-code-nft-marketplace/cis2-multi/.gitignore
> +Cargo.lock
The lock file for smart contracts should be committed.

2023-04-12 18:53 UTC, abizjak commented on low-code-nft-marketplace/cis2-multi/Cargo.toml
> +name = "cis2-multi"
WHy is this contract here? We have a contract named the same in the rust-smart-contracts repository. We should not duplicate things since it's hard to maintain.

If there is something missing in that example maybe we can just add it there instead of duplicating most of it here.

2023-04-12 18:53 UTC, abizjak commented on low-code-nft-marketplace/market-ui/README.md
> +Currently the browser wallet does not allow to deploy modules to Concordium chain. However [node-cli](https://github.com/chainorders/concordium-contracts-node-cli) and [concordium client](https://git
Can we just point to the client here since that is controlled by us.

2023-04-12 18:53 UTC, abizjak commented on low-code-nft-marketplace/market-ui/src/components/Cis2FindInstanceOrInit.tsx
> +	account: string;
I think there should be an AccountAddress type. Why is that not being used here, and in most other Cis2* pages?

2023-04-12 18:53 UTC, abizjak commented on low-code-nft-marketplace/market-ui/src/index.tsx
> +reportWebVitals();
Why is this needed?

2023-04-12 18:53 UTC, abizjak commented on low-code-nft-marketplace/market-ui/src/models/Cis2Client.ts
> +export async function isOperator(
This CIS2 client here is similar to waht we have in the Rust SDK. It would be great to add this to the web/node SDK instead of having it here.

That was actually one of the items on the list we wanted to do this quarter. Can you make a PR with that to the node SDK?

2023-04-12 18:53 UTC, abizjak commented on low-code-nft-marketplace/market-ui/src/models/Cis2Deserializer.ts
> +	readTokenAmount(): bigint {
Also this should be part of the web SDK.

2023-04-12 18:53 UTC, abizjak commented on low-code-nft-marketplace/market-ui/src/models/Cis2Types.d.ts
> +	display: Display;
What about thumbnail and other attributes? Why are they not here?

2023-04-12 18:53 UTC, abizjak commented on low-code-nft-marketplace/market-ui/src/models/Cis2Types.d.ts
> +export interface Attribute {
It would be useful to move all of this to the nodeJS/web sDK. And document what all of these are.

2023-04-12 18:53 UTC, abizjak commented on low-code-nft-marketplace/market-ui/src/models/ConcordiumContractClient.ts
> +export async function updateContract<T>(
From reading the documentation this looks essentially like sendTransaction. But there is an important waiting at the end for finalization. That should be included in the documentation.

2023-04-12 18:53 UTC, abizjak commented on low-code-nft-marketplace/market-ui/src/models/ConcordiumDeserializer.ts
> +export class ConcordiumDeserializer extends BufferStream {
This class also belongs to the SDK I think.

2023-04-12 18:53 UTC, abizjak commented on low-code-nft-marketplace/mint-ui/src/models/BufferStream.ts
> +	readUBigInt(): bigint {
This BufferStream type is duplicated. We cannot do this, it is a pain for maintenance.

If you move it to the SDK instead then there is no need to do this.

2023-04-12 18:53 UTC, abizjak commented on low-code-nft-marketplace/mint-ui/src/models/Cis2Client.ts
> +export const enum MethodName {
This entire file is just duplicated. We are not doing this.

2023-04-12 18:53 UTC, abizjak commented on low-code-nft-marketplace/mint-ui/src/models/Cis2Deserializer.ts
> +export class Cis2Deserializer extends ConcordiumDeserializer {
Also this is duplicated.

2023-04-12 18:53 UTC, abizjak commented on low-code-nft-marketplace/mint-ui/src/models/Cis2Types.d.ts
> +import { ContractAddress } from "@concordium/web-sdk";
This file is duplicated.

2023-04-12 18:53 UTC, abizjak commented on low-code-nft-marketplace/mint-ui/src/models/PinataClient.ts
> +import { default as axios } from "axios";
This file is duplicated.

2023-05-05 23:54 UTC, parv0888 commented on low-code-nft-marketplace/market-ui/src/models/Cis2Client.ts
> +export async function isOperator(
done

2023-05-05 23:55 UTC, parv0888 commented on low-code-nft-marketplace/market-ui/src/models/Cis2Deserializer.ts
> +	readTokenAmount(): bigint {
done

2023-05-05 23:55 UTC, parv0888 commented on low-code-nft-marketplace/market-ui/src/models/Cis2Types.d.ts
> +	display: Display;
they are not used in the project

2023-05-05 23:55 UTC, parv0888 commented on low-code-nft-marketplace/market-ui/src/models/ConcordiumDeserializer.ts
> +export class ConcordiumDeserializer extends BufferStream {
done

2023-05-05 23:56 UTC, parv0888 commented on low-code-nft-marketplace/mint-ui/src/models/BufferStream.ts
> +	readUBigInt(): bigint {
done

2023-05-05 23:56 UTC, parv0888 commented on low-code-nft-marketplace/mint-ui/src/models/Cis2Client.ts
> +export const enum MethodName {
abstracted to common-ui

2023-05-05 23:56 UTC, parv0888 commented on low-code-nft-marketplace/mint-ui/src/models/Cis2Deserializer.ts
> +export class Cis2Deserializer extends ConcordiumDeserializer {
abstracted to common-ui

2023-05-05 23:56 UTC, parv0888 commented on low-code-nft-marketplace/mint-ui/src/models/Cis2Types.d.ts
> +import { ContractAddress } from "@concordium/web-sdk";
abstracted to common-ui

2023-05-05 23:56 UTC, parv0888 commented on low-code-nft-marketplace/mint-ui/src/models/PinataClient.ts
> +import { default as axios } from "axios";
abstracted to common-ui

2023-05-06 20:45 UTC, parv0888 commented on low-code-nft-marketplace/README.md
> +This repository provides sample implementations of following ways in which a developer can interact with an on chain contract on Concordium.This repo includes both minting tool and the NFT Marketplac
changed

2023-05-06 20:45 UTC, parv0888 commented on low-code-nft-marketplace/cis2-market/.gitignore
> +Cargo.lock
removed

2023-05-06 23:16 UTC, parv0888 commented on low-code-nft-marketplace/cis2-market/src/cis2_client.rs
> +    pub(crate) fn supports_cis2<S: HasStateApi, T: IsTokenId, A: IsTokenAmount + Copy>(
changed to `pub`

2023-05-06 23:17 UTC, parv0888 commented on low-code-nft-marketplace/cis2-market/src/cis2_client.rs
> +                SupportResult::SupportBy(_) => false,
removed the choice and changed `transfer` function to respect `supports` response

2023-05-06 23:22 UTC, parv0888 commented on low-code-nft-marketplace/cis2-market/src/cis2_client.rs
> +    fn invoke_contract_read_only<
removed the function. inlined separately to calling functions.
Added documentation to all the functions.

2023-05-06 23:22 UTC, parv0888 commented on low-code-nft-marketplace/cis2-market/src/cis2_client.rs
> +        entrypoint_name: &str,
used `EntrypointName`

2023-05-06 23:24 UTC, parv0888 commented on low-code-nft-marketplace/cis2-market/src/params.rs
> +    pub cis_contract_address: ContractAddress,
done

2023-05-06 23:26 UTC, parv0888 commented on low-code-nft-marketplace/cis2-market/src/params.rs
> +    pub commission: u16,
done

2023-05-06 23:32 UTC, parv0888 commented on low-code-nft-marketplace/cis2-market/src/state.rs
> +    pub(crate) fn get_listed(
added

2023-05-06 23:36 UTC, parv0888 commented on low-code-nft-marketplace/cis2-multi/.gitignore
> +Cargo.lock
contract removed

2023-05-06 23:37 UTC, parv0888 commented on low-code-nft-marketplace/cis2-multi/Cargo.toml
> +name = "cis2-multi"
contract removed from here and a PR raised in the rust-smart-contracts repository
https://github.com/Concordium/concordium-rust-smart-contracts/pull/254

2023-05-06 23:37 UTC, parv0888 commented on low-code-nft-marketplace/market-ui/src/components/Cis2FindInstanceOrInit.tsx
> +	account: string;
The wallet provider / WallepApi returns the account address as string

2023-05-06 23:39 UTC, parv0888 commented on low-code-nft-marketplace/market-ui/src/index.tsx
> +reportWebVitals();
removed

2023-05-06 23:41 UTC, parv0888 commented on low-code-nft-marketplace/market-ui/src/components/Cis2FindInstanceOrInit.tsx
> +	account: string;
Also the CIS2.* methods accept account address as string

2023-05-06 23:45 UTC, parv0888 commented on low-code-nft-marketplace/market-ui/src/models/Cis2Types.d.ts
> +export interface Attribute {
the latest version SDK. with CIS2 support does not include it. 
Will update when the SDK exports the type in question.

2023-05-06 23:45 UTC, parv0888 commented on low-code-nft-marketplace/market-ui/src/models/ConcordiumContractClient.ts
> +export async function updateContract<T>(
done

2023-05-07 00:15 UTC, parv0888 commented on .github/workflows/rust-fmt-lint.yaml
> +                  args: --manifest-path ${{ matrix.crates }} -- -D warnings
reverted

2023-05-07 00:18 UTC, parv0888 commented
> Most of it looks pretty good, but there are a few things that need to be changed
> 
> * I don't think we should have a duplicate copy of the CIS2-multi contract. We  should work to get the one in rust-smart-contracts modified if practical.
> * There is a bunch of duplication for generic stuff for interacting with CIS2 contracts. That should be moved to the node SDK and the duplication should be removed.
> * The typescript projects should have linting as well.
> * Cargo.lock files should be committed for contracts.

@abizjak  : We have done our best efforts to fix the issues and to address the comments. Kindly review again

2023-06-20 05:21 UTC, parv0888 commented on low-code-nft-marketplace/cis2-market/src/cis2_client.rs
> +pub const CIS2_STANDARD_IDENTIFIER_STR: &str = "CIS-2";
https://github.com/Concordium/concordium-rust-smart-contracts/pull/304

2023-07-21 12:14 UTC, DOBEN commented
I get errors running the `mint-ui` front end. Using a fixed version ` "@concordium/browser-wallet-api-helpers": "2.5.0" in both packages resolves it. There is some other output when running `yarn build` in `mint-ui` folder, please have a look.

```
everTS2345: Argument of type 'import(".../LowCodeMareketPlace/concordium-dapp-examples/low-code-nft-marketplace/mint-ui/node_modules/@concordium/browser-wallet-api-helpers/lib/wallet-api-types").WalletApi' is not assignable to parameter of type 'import(".../LowCodeMareketPlace/concordium-dapp-examples/low-code-nft-marketplace/common-ui/node_modules/@concordium/browser-wallet-api-helpers/lib/wallet-api-types").WalletApi'.
    22 |     setState({ ...state, processing: true });
    23 |
  > 24 |     initContract(props.provider, props.contractInfo, props.account)
       |                  ^^^^^^^^^^^^^^
    25 |       .then((address) => {
    26 |         setState({ ...state, processing: false });
    27 |         props.onDone(address, props.contractInfo);`

2023-07-21 12:23 UTC, DOBEN commented
Some suggestions for the future (in new PRs if we decide to incorporate it) once we get the first version merged and we discuss the :
- [ ] Add versions somewhere visible at the front end
- [ ] Add Dockerfile so the front ends can also run via a Docker container
- [ ] Add Filter for the NFTs listed (e.g. user can search by creator, by collection, by price, by newest)

2023-07-21 12:26 UTC, DOBEN commented
Users can end up in a weird situation where they have uploaded something to pinata (adding pinata metadatHash) and also add a regular manual metaData hash. Consider disabling the button `addNewMetaDataHash` when the user already has successfully uploaded something to IPFS (is going down the IPFS route). 
![WeirdSituationWhereYouMintBothPinataAndRegularMetaDataHashAtTheSameTime](https://github.com/Concordium/concordium-dapp-examples/assets/13039169/14f47c4c-3ed8-4b11-826f-1b7a54eff1f0)

2023-07-21 12:33 UTC, DOBEN commented
When clicking the “Create My MarketPlace” page and deploying a new contract an empty white page appears. Consider adding some information for the user what to do next. It is fair enough to link the developer documentation and let them know where to continue reading or just explain in text form that they now need to run the whole front end again but with the new smart contract index set in the `constant.ts` file.
![CreateNewMarketPlaceEmptyPage](https://github.com/Concordium/concordium-dapp-examples/assets/13039169/f56e7e6f-e15c-43fe-8516-ba0597828c24)

2023-07-21 12:37 UTC, DOBEN commented
Suggestion: We need to explain what "primary seller royalties" are. It is not the creator but the person the first sells the NFT on this marketplace that can set the royalties. Maybe that is part of the developer documentation then that is fair enough. It would be super nice if there is an explanation at the front end explaining how the royalties work in this marketplace.

![PrimarySellerRoyalties](https://github.com/Concordium/concordium-dapp-examples/assets/13039169/76a44aaf-5407-4fa8-86f6-e9e393b1c573)

2023-07-21 13:06 UTC, DOBEN commented
I am not a fan of hard-coding the pinata gateway/provider into the metaData in the smart contract when minting a token via the front end. 
![notHardCodingTheIPFSGateWayProviderIntoTheMetaDataHash](https://github.com/Concordium/concordium-dapp-examples/assets/13039169/09de282b-9b92-4c94-94e4-4ad2dc2149d4)

 E.g. if Pinata decides to change its Gateway-URL one day then all the metadata links are broken or the company goes out of business. Generally, I wouldn’t want to hardcode third-party URLs into smart contract code that my NFT collection now depends on that third party.
![howIPFSMetaDataIsStoredInContractsUsually](https://github.com/Concordium/concordium-dapp-examples/assets/13039169/cc8bf747-4d3f-40b3-9855-3bedf547650d)

Usually, only the IPFS  hash (not the gateway) is hardcoded in the smart contract as metadata. The marketplace infrastructure does then resolve the IPFS hash and uses the gateway that they want to use. For e.g. big NFT marketplaces they can not rely on the free pinata gateway which is rate-limited but rather have their own gateway or a paid/high-performing one.

2023-07-21 13:33 UTC, DOBEN reviewed
This project is a great addition to our tools. Well written and it can serve as a good start for people to create their own projects. There went a lot of work in this PR and this is appreciated. So depending on how polished we want to get it, I am fine if we decide to address some of the remaining comments in future PRs to get this massive PR merged.

I had some hiccups with the pinata/front-end flow so (the keys that I just generated didn’t work reliably but I got some borrowed keys that worked). Since users can skip that step, we are good to go for the first version. If we get some more feedback about the pinata flow, we can improve on it to make it easier for people to get through e.g. by improving the documentation how and which types of keys they need to generate.

- Does the user have to wait after creating the pinata key (until it is activated)?
- Can I upload the same picture (the ipfs hash has not changed) in the flow several times?

2023-07-21 14:01 UTC, bogacyigitbasi commented
Hey @DOBEN , here are some explanations about how it works/why?
- The reason why we have both upload with Pinata/IPFS + Add New Metadata is to allow the minter to use both IPFS upload(metadata generator) and if he has metadata already. So he will mint multiple tokens. 
- For the UI improvements, we have some in the next versions, first one is limited in terms of the functionalities. 
- For the IPFS gateway for pinata is actually defined as a variable in the _Constants.ts_ file. Users can choose it to store only IPFS hash, "_gateway.pinata.ipfs_" is optional. The same hash should also work with "_https://ipfs.io/ipfs_" but the IPFS servers sometimes require too much time to respond. For reuploading it, there is nothing implemented that prevents it. We decided that should be something the custom use case owner can decide to allow/disallow it.
- Royalties are similarly explained in the documentation as far as I remember, we may update it if it is not enough though. 
- We will address the suggested changes regarding links, comments and rest. 
Overall, thank you for the comments. This tool is just for setting a baseline, when all the changes are addressed there will be a video showing how to use it effectively (in addition to the existing document)

2023-08-08 22:40 UTC, parv0888 commented on low-code-nft-marketplace/cis2-market/src/state.rs
> +pub struct TokenInfo<T: Serial + Deserial> {
done

2023-08-08 22:40 UTC, parv0888 commented on low-code-nft-marketplace/cis2-market/src/state.rs
> +pub struct TokenOwnerInfo<T: Serial + Deserial> {
done

2023-08-16 20:35 UTC, parv0888 commented on low-code-nft-marketplace/cis2-market/src/lib.rs
> +/// This function is the typical buuy function of a Marketplace where one
done

2023-08-16 20:44 UTC, parv0888 commented on low-code-nft-marketplace/cis2-market/src/state.rs
> +        );
done

2023-08-16 21:04 UTC, parv0888 commented on low-code-nft-marketplace/market-ui/package.json
> +  "homepage": "https://bogacyigitbasi.github.io/low-code-nft-marketplace",
done

2023-08-16 21:36 UTC, parv0888 commented on low-code-nft-marketplace/common-ui/src/models/Cis2Client.ts
> +import * as connClient from "./ConcordiumContractClient";
done

2023-08-16 21:44 UTC, parv0888 commented on low-code-nft-marketplace/README.md
> +Please do note that this is **not** an exhaustive list of the languages supported by Concordium. There are are SDK's present to interact with the contracts using multiple other languages. A complete
done

2023-08-16 21:49 UTC, parv0888 commented on low-code-nft-marketplace/common-ui/src/models/Cis2Client.ts
> +const hexToUnsignedInt = (inputStr: string) => {
done

2023-08-16 21:49 UTC, parv0888 commented on low-code-nft-marketplace/market-ui/.eslintrc
> +{
removed

2023-08-16 21:49 UTC, parv0888 commented on low-code-nft-marketplace/market-ui/.prettierrc.json
> +{
removed

2023-08-16 21:52 UTC, parv0888 commented on low-code-nft-marketplace/market-ui/README.md
> +Currently the [browser wallet](https://github.com/Concordium/concordium-browser-wallet) does not allow to deploy modules to Concordium chain. However [concordium client](https://github.com/chainorder
done

2023-08-16 21:55 UTC, parv0888 commented on low-code-nft-marketplace/README.md
> +
the updated docs adds the information to install dependencies and build it.

2023-08-16 21:56 UTC, parv0888 commented on low-code-nft-marketplace/cis2-market/src/cis2_client.rs
> +//! - `transfer` : Calls [`transfer`](https://proposals.concordium.software/CIS/cis-2.html#transfer)
`cis2-client` has been moved to `concoridium-rust-smart-contract` repo

2023-08-16 21:56 UTC, parv0888 commented on low-code-nft-marketplace/cis2-market/src/cis2_client.rs
> +        let is_operator = is_operators
`cis2-client` has been moved to `concoridium-rust-smart-contract` repo

2023-08-16 21:56 UTC, parv0888 commented on low-code-nft-marketplace/cis2-market/src/cis2_client.rs
> +        let balance = balances
`cis2-client` has been moved to `concoridium-rust-smart-contract` repo

2023-08-16 21:58 UTC, parv0888 commented on low-code-nft-marketplace/mint-ui/README.md
> +Currently the browser wallet does not allow to deploy modules to Concordium chain. However [node-cli](https://github.com/chainorders/concordium-contracts-node-cli) and [concordium client](https://git
done

2023-08-16 22:07 UTC, parv0888 commented on low-code-nft-marketplace/common-ui/src/models/ConcordiumContractClient.ts
> + * @param account  Account to Update the contract with.
done

2023-08-16 22:09 UTC, parv0888 commented on low-code-nft-marketplace/market-ui/README.md
> +    - [Cis2UpdateOperator](./src/components/Cis2UpdateOperator.tsx) : `updateOperator` is the above is not true.
done

2023-08-16 22:10 UTC, parv0888 commented on low-code-nft-marketplace/market-ui/README.md
> +    - [MarketplaceTokensList](./src/components/MarketplaceTokensList.tsx) : Used to get a list of buy able tokens from the Marketplace Contract, It uses following components
done

2023-08-16 22:11 UTC, parv0888 commented on low-code-nft-marketplace/market-ui/README.md
> +    - [Cis2FindInstanceOrInit](./src/components/Cis2FindInstanceOrInit.tsx) : Gives the user either the option to Find a CIS2 compliant instance Or Initialize a new one using config value `MULTI_CONT
done

2023-08-16 22:12 UTC, parv0888 commented on low-code-nft-marketplace/market-ui/README.md
> +    - [Cis2UpdateOperator](./src/components/Cis2UpdateOperator.tsx) : `updateOperator` is the above is not true.
done

2023-08-16 22:12 UTC, parv0888 commented on low-code-nft-marketplace/market-ui/README.md
> +    - [Cis2FindInstanceOrInit](./src/components/Cis2FindInstanceOrInit.tsx) : Gives the user either the option to Find a CIS2 compliant instance Or Initialize a new one using config value `MULTI_CONT
done

2023-08-16 22:25 UTC, parv0888 commented on low-code-nft-marketplace/market-ui/src/Constants.ts
> +  "ffff03010000000a000000636973325f6d756c7469000a0000000900000062616c616e63654f6606100114000200000008000000746f6b656e5f69641d0007000000616464726573731502000000070000004163636f756e7401010000000b080000
done

2023-08-21 10:39 UTC, DOBEN commented on low-code-nft-marketplace/README.md
> +    tsc -b
This means people have to download `tsc` and set it up. It would be better to just usa a `yarn` command that builds all workspace projects.

E.g. `yarn build:all` :

https://github.com/Concordium/concordium-browser-wallet/blob/main/package.json#L17C10-L17C20

2023-08-21 10:39 UTC, DOBEN commented on .gitmodules
>  	url = ../concordium-rust-sdk.git
Your submodule link is broken:
```git submodule update --recursive --init```

```
ERROR: Repository not found.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

![submoduleError](https://github.com/Concordium/concordium-dapp-examples/assets/13039169/c0b20ac8-e8ba-478d-9ad1-b452c895dc39)


This submodule link does not exist:

https://github.com/bogacyigitbasi/concordium-rust-sdk/tree/35cd980ba4c6ff63079de4498f3a52953b2da4ac

2023-08-21 10:39 UTC, DOBEN commented on .gitmodules
> +	url = git@github.com:Concordium/concordium-rust-smart-contracts.git
The submodule link should be relative similar to the above one.

2023-08-21 10:39 UTC, DOBEN commented on low-code-nft-marketplace/README.md
> +
I get errors that the metadata files cannot be fetched at the front end. This could be maybe because of rate-limiting of the pinata gateway. I assume the pinata gateway is hardcoded in the NFT metadata in the smart contract so even changing “pinata gateway” to “https://ipfs.io/ipfs/” in the constant file did not help.
 
 https://github.com/Concordium/concordium-dapp-examples/pull/8#issuecomment-1645560367
 
 There is an extra `/` in the URL which should not be there:
 "https://gateway.pinata.cloud/ipfs//QmfM1EZ6iACRtfhHtwyk31s4XkRTCcPC4DoKRS1KD3JMn1"
 Should be:
  "https://gateway.pinata.cloud/ipfs/QmfM1EZ6iACRtfhHtwyk31s4XkRTCcPC4DoKRS1KD3JMn1"
![pinata](https://github.com/Concordium/concordium-dapp-examples/assets/13039169/ad1ea805-7e7a-4d1f-9fbe-f1f3a8b3b891)
![pinata2](https://github.com/Concordium/concordium-dapp-examples/assets/13039169/d7c51f62-c320-4347-960e-1342465f7b24)
![pinata3](https://github.com/Concordium/concordium-dapp-examples/assets/13039169/43e75def-5678-45f9-a515-b7005d61be60)

2023-08-21 10:53 UTC, parv0888 commented on low-code-nft-marketplace/README.md
> +    tsc -b
sure. it will have to use tsc internally to build typescript. Since typescript is present in the dev dependencies it can be used from `node_modules` ie. `npx tsc -b`. I will update this

2023-08-21 11:51 UTC, parv0888 commented on .gitmodules
>  	url = ../concordium-rust-sdk.git
Since the modules are relative and PR is from a forked repo. The submodules might be giving an issue. 
This is the output of the same command on my system. 
```
Submodule 'concordium-rust-sdk' (git@github.com:parv0888/concordium-rust-sdk.git) registered for path 'deps/concordium-rust-sdk'
Cloning into '/home/parv0888/work/work/tmp/concordium-dapp-examples/deps/concordium-rust-sdk'...
remote: Enumerating objects: 518, done.
remote: Counting objects: 100% (518/518), done.
remote: Compressing objects: 100% (160/160), done.
remote: Total 518 (delta 352), reused 458 (delta 343), pack-reused 0
Receiving objects: 100% (518/518), 261.42 KiB | 320.00 KiB/s, done.
Resolving deltas: 100% (352/352), completed with 23 local objects.
From github.com:parv0888/concordium-rust-sdk
 * branch                adf27b44ee013c90ae93c4eed7952c9bdb8e9389 -> FETCH_HEAD
Submodule path 'deps/concordium-rust-sdk': checked out 'adf27b44ee013c90ae93c4eed7952c9bdb8e9389'
Submodule 'concordium-base' (git@github.com:parv0888/concordium-base.git) registered for path 'deps/concordium-rust-sdk/concordium-base'
Cloning into '/home/parv0888/work/work/tmp/concordium-dapp-examples/deps/concordium-rust-sdk/concordium-base'...
remote: Enumerating objects: 4483, done.
remote: Counting objects: 100% (4483/4483), done.
remote: Compressing objects: 100% (1475/1475), done.
remote: Total 4483 (delta 2841), reused 4080 (delta 2674), pack-reused 0
Receiving objects: 100% (4483/4483), 1.70 MiB | 1.28 MiB/s, done.
Resolving deltas: 100% (2841/2841), completed with 20 local objects.
From github.com:parv0888/concordium-base
 * branch              492ba5410e1aee458fb878c854a7027a062b5238 -> FETCH_HEAD
Submodule path 'deps/concordium-rust-sdk/concordium-base': checked out '492ba5410e1aee458fb878c854a7027a062b5238'
Submodule 'concordium-contracts-common' (git@github.com:parv0888/concordium-contracts-common.git) registered for path 'deps/concordium-rust-sdk/concordium-base/concordium-contracts-common'
Submodule 'concordium-grpc-api' (git@github.com:parv0888/concordium-grpc-api.git) registered for path 'deps/concordium-rust-sdk/concordium-base/concordium-grpc-api'
Cloning into '/home/parv0888/work/work/tmp/concordium-dapp-examples/deps/concordium-rust-sdk/concordium-base/concordium-contracts-common'...
Cloning into '/home/parv0888/work/work/tmp/concordium-dapp-examples/deps/concordium-rust-sdk/concordium-base/concordium-grpc-api'...
remote: Enumerating objects: 910, done.
remote: Counting objects: 100% (515/515), done.
remote: Compressing objects: 100% (188/188), done.
remote: Total 910 (delta 364), reused 433 (delta 325), pack-reused 395
Receiving objects: 100% (910/910), 329.04 KiB | 299.00 KiB/s, done.
Resolving deltas: 100% (605/605), completed with 9 local objects.
From github.com:parv0888/concordium-contracts-common
 * branch            68c028bb42a0ba62cf423fac9f6799b6607e9f19 -> FETCH_HEAD
Submodule path 'deps/concordium-rust-sdk/concordium-base/concordium-contracts-common': checked out '68c028bb42a0ba62cf423fac9f6799b6607e9f19'
remote: Enumerating objects: 135, done.
remote: Counting objects: 100% (135/135), done.
remote: Compressing objects: 100% (40/40), done.
remote: Total 135 (delta 76), reused 108 (delta 70), pack-reused 0
Receiving objects: 100% (135/135), 46.70 KiB | 214.00 KiB/s, done.
Resolving deltas: 100% (76/76), completed with 2 local objects.
From github.com:parv0888/concordium-grpc-api
 * branch            13e23942735a427b188b6a27909044ff6493f50a -> FETCH_HEAD
Submodule path 'deps/concordium-rust-sdk/concordium-base/concordium-grpc-api': checked out '13e23942735a427b188b6a27909044ff6493f50a'
```

Would you advise changing the submodules to an absolute path?

2023-08-21 11:53 UTC, parv0888 commented on .gitmodules
>  	url = ../concordium-rust-sdk.git
The line of code referenced here was part of the code base when we forked it. 
@abizjak any recommendations? Tagging you since it seems this was added.

2023-08-21 11:53 UTC, abizjak commented on .gitmodules
> +	url = git@github.com:Concordium/concordium-rust-smart-contracts.git
Why do we need this submodule again? The updated rust libraries have been released with cis2client and other bugfixes.

2023-08-21 11:54 UTC, abizjak commented on .gitmodules
>  	url = ../concordium-rust-sdk.git
We should always have relative submodules. Otherwise there are problems checking out repos, e.g., if the user does not have the right ssh access to the repo.

2023-08-21 12:01 UTC, parv0888 commented on .gitmodules
> +	url = git@github.com:Concordium/concordium-rust-smart-contracts.git
@abizjak  : apologies for the confusion. Just relaized it was released today. 
https://github.com/Concordium/concordium-rust-smart-contracts/tree/releases/concordium-cis2/5.0.0
Thanks 

Will update the core to reflect the same.

2023-08-21 16:07 UTC, DOBEN commented on low-code-nft-marketplace/README.md
> +    tsc -b
can you please update the readme with this information.

2023-08-21 16:09 UTC, DOBEN commented on low-code-nft-marketplace/README.md
> +
@parv0888 Any suggestion to the metadata load issue?

2023-08-21 17:42 UTC, parv0888 commented on .gitmodules
>  	url = ../concordium-rust-sdk.git
@DOBEN since we are checking out 
git@github.com:bogacyigitbasi/concordium-dapp-examples.git
and the submodules are present for the relative path git@github.com:bogacyigitbasi/
i think this is causing the error. 

If you manually checkout the submodules (Without git submodule command)
then it should work.

2023-08-21 17:52 UTC, DOBEN commented on .gitmodules
>  	url = ../concordium-rust-sdk.git
How do you manually checkout the submodule link (could you give the commands please)? Do you copy-paste the `concordium-rust-sdk `into the `deps` folder?

2023-08-21 23:08 UTC, parv0888 commented on low-code-nft-marketplace/README.md
> +
@DOBEN  : this is done

2023-08-22 12:13 UTC, DOBEN approved these changes
Well done. This project is a valuable contribution to our dApp examples. Thanks for your continued effort in working on it.

2023-08-22 12:56 UTC, merged